---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-stress
  labels:
    app: stress
spec:
  selector:
    matchLabels:
      stress-area: here
  replicas: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stress-area: here
    spec:
      containers:
      - name: container-stress
        image: mohsenmottaghi/container-stress:latest
        command: ["stress", "--verbose", "--vm", "1", "--vm-bytes", "1024"]
         # If you don`t know why you should define these elements, Don`t change them !
         # Check commands in README.md
        resources:
          limits:
            memory: "1200Mi"
            cpu: "1000m"
          requests:
            memory: "1000Mi"
            cpu: "100m"
